name: 🚀 Deploy to Server

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    name: SSH Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy over SSH
        uses: appleboy/ssh-action@master
        with:
          host:  45.159.231.9 
          username: root 
          key: ${{ secrets.SSH_KEY }} 
          port: 22 
          script: |
            cd /var/www/goo-cast-reservation-system/  
            git pull origin main
            cd client 
            npm install
            npm run build
            cd ../server
            npm install
            pm2 restart app              
